### ISSUE TITLE
1.0.2_1.11.2 crashes dedicated server Forge 1.11.2 build 2366

### ISSUE THREAD

**Issue by kreezxil** [BigXplosion/ProjectTable#1]
Notes:
     on startup, appears to be looking for client side classes, it's also an NPE

crash report:
https://gist.github.com/d3f5807a90f8cc7e26b8f6f00ff11387

fml server latest:
https://gist.github.com/432c3f74f4a8e2249ceea214040d64f4

**Comment by BigXplosion** [comment]
Well that is a huge derp on my part... It's not looking for a clientside class though, I just made an error typing the path to a class... 

Thanks for the good issue report!
Fix is being uploaded for 1.11 and 1.12 as we speak
