### ISSUE TITLE
GUI not overriding drawScreen()

### ISSUE THREAD

**Issue by ChloeDawn** [BigXplosion/ProjectTable#2]
You are not overriding `drawScreen()` in your GUIs, so the background and tooltips are not being drawn.

**EDIT:** Your tooltips appear to be getting drawn, so perhaps you overlooked `drawDefaultBackground()`?

**Mod version:** [1.1.1](https://minecraft.curseforge.com/projects/projecttable/files/2442384)
**Forge version:** [1.12-14.21.1.2387](http://files.minecraftforge.net/maven/net/minecraftforge/forge/1.12-14.21.1.2387/forge-1.12-14.21.1.2387-changelog.txt)

**See this pull request here for more information https://github.com/copygirl/WearableBackpacks/pull/33**

**Project table GUI:**

![](http://i.imgur.com/WAHFNVD.png)

**Player inventory GUI:**

![](http://i.imgur.com/NNHrntT.png)

**Comment by BigXplosion** [comment]
Oh yeah, I seem to have overlook the `drawDefaultBackground()`. Thanks for noticing! 

Fixed in next release
